eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: passengers
          uri: http://localhost:8090
          predicates:
            - Path=/api/passengers/**
        - id: trains
          uri: http://localhost:8070
          predicates:
            - Path=/api/trains/**
  application:
    name:
      gateway